/**
 * ocrWorker.js
 *
 * Web Worker that runs a vision-to-text generation model (TrOCR) via Transformers.js.
 * 
 * Messages:
 *   "init"    → Load the HuggingFace model. Posts { type: 'ready' }.
 *   "extract" → Receive ImageBitmap, crop, run inference, return text string.
 *               Posts { type: 'result', text: '...' }.
 *   "dispose" → Free up the InferenceSession resources.
 */

import { pipeline, env, RawImage } from '@huggingface/transformers';

// Configuration
env.allowLocalModels = false; // Fetch from HF hub
env.backends.onnx.wasm.numThreads = 1; // Avoid COOP/COEP SharedArrayBuffer issues

let extractorPipeline = null;

self.onmessage = async (e) => {
    const { type, data } = e.data;

    try {
        switch (type) {
            case 'init':
                if (!extractorPipeline) {
                    self.postMessage({ type: 'progress', status: 'Loading OCR model...' });
                    
                    // Initialize the pipeline
                    // Using small printed for accurate document OCR
                    extractorPipeline = await pipeline('image-to-text', 'Xenova/trocr-small-printed', {
                        progress_callback: (pl) => {
                            self.postMessage({ type: 'progress', data: pl });
                        }
                    });
                }
                self.postMessage({ type: 'ready' });
                break;

            case 'extract':
                if (!extractorPipeline) throw new Error('OCR model not initialized. Send "init" first.');
                
                const { imageBitmap } = data;
                
                // Render the ImageBitmap onto an OffscreenCanvas to extract pixel data
                const canvas = new OffscreenCanvas(imageBitmap.width, imageBitmap.height);
                const ctx = canvas.getContext('2d');
                ctx.drawImage(imageBitmap, 0, 0);
                
                const imageData = ctx.getImageData(0, 0, imageBitmap.width, imageBitmap.height);
                
                // Transformers.js expects RawImage representation
                const rawImage = new RawImage(imageData.data, imageData.width, imageData.height, 4);
                
                // TrOCR models typically expect 3-channel RGB image
                const rgbImage = rawImage.convert(3);

                // Run generation
                // Note: max_new_tokens limits generation. For large blocks of text, we may need to increase it.
                // 256 is usually sufficient for single bounding boxes generated by layout detection.
                const results = await extractorPipeline(rgbImage, { max_new_tokens: 256 });
                
                let text = '';
                if (results && results.length > 0 && results[0].generated_text) {
                    text = results[0].generated_text.trim();
                }

                self.postMessage({ type: 'result', text });
                break;

            case 'dispose':
                if (extractorPipeline) {
                    await extractorPipeline.dispose();
                    extractorPipeline = null;
                }
                self.postMessage({ type: 'disposed' });
                break;

            default:
                self.postMessage({ type: 'error', error: `Unknown message type: ${type}` });
        }
    } catch (err) {
        self.postMessage({ type: 'error', error: err.message });
    }
};
